"""
reporting.py
============
Render a log-analysis report (Markdown or HTML) from a LogTracer.

Pure library-mode by default (no LLM) — uses summary / frequency / health /
last incident / duration. Set include_root_cause=True to also run the LLM
root-cause analysis (requires a configured provider).
"""

import html as _html
from typing import Dict, Optional


def build_report(
    tracer,
    fmt: str = "markdown",
    date: Optional[str] = None,
    from_dt: Optional[str] = None,
    to_dt: Optional[str] = None,
    include_root_cause: bool = False,
) -> str:
    """Collect analysis from `tracer` and render it as 'markdown' or 'html'."""
    data = _collect(tracer, date, from_dt, to_dt, include_root_cause)
    fmt = (fmt or "markdown").lower()
    if fmt in ("md", "markdown"):
        return _render_markdown(data)
    if fmt == "html":
        return _render_html(data)
    raise ValueError(f"Unknown report format '{fmt}'. Use 'markdown' or 'html'.")


def _collect(tracer, date, from_dt, to_dt, include_root_cause) -> Dict:
    summary = tracer.summary(date=date, from_dt=from_dt, to_dt=to_dt)
    health = tracer.health_check()
    duration = tracer.incident_duration(date=date, from_dt=from_dt, to_dt=to_dt)
    last = tracer.last_incident(date=date, from_dt=from_dt, to_dt=to_dt)
    last_rows = [
        {
            "timestamp": (
                e["timestamp"].strftime("%Y-%m-%d %H:%M:%S")
                if e.get("timestamp") and hasattr(e["timestamp"], "strftime")
                else str(e.get("timestamp"))
            ),
            "error_type": e.get("error_type", ""),
            "primary_error": e.get("primary_error", ""),
        }
        for e in (last or [])
    ]
    root = None
    if include_root_cause:
        try:
            root = tracer.root_cause_analysis(date=date, from_dt=from_dt, to_dt=to_dt)
        except Exception as e:  # never let a report crash on LLM issues
            root = {"error": str(e)}
    return {
        "file": getattr(tracer, "file_path", "log"),
        "summary": summary,
        "frequency": summary.get("frequency", {}),
        "health": health,
        "duration": duration,
        "last_incident": last_rows,
        "root_cause": root,
    }


# ── Markdown ───────────────────────────────────────────────────────
def _render_markdown(d: Dict) -> str:
    s, h = d["summary"], d["health"]
    lines = [
        f"# Log Analysis Report — `{d['file']}`",
        "",
        f"**Status:** {h.get('status', '?')} — {h.get('summary', '')}",
        "",
        "## Summary",
        f"- Total entries: **{s.get('total_entries', 0)}**",
        f"- Total errors: **{s.get('total_errors', 0)}**",
        f"- Incidents (clusters): **{s.get('total_clusters', 0)}**",
        f"- First error: {s.get('first_error') or '—'}",
        f"- Last error: {s.get('last_error') or '—'}",
        "",
        "## Error frequency",
    ]
    freq = d["frequency"]
    if freq:
        lines += ["| Error type | Count |", "|---|---|"]
        lines += [f"| {k} | {v} |" for k, v in freq.items()]
    else:
        lines.append("_No errors found._")

    dur = d["duration"]
    lines += ["", "## Last incident"]
    if dur and "duration_human" in dur:
        lines.append(f"_Duration: {dur['duration_human']} "
                     f"({dur.get('start')} -> {dur.get('end')})_")
    if d["last_incident"]:
        lines += ["", "| Time | Type | Message |", "|---|---|---|"]
        for r in d["last_incident"]:
            msg = r["primary_error"].replace("|", "\\|")
            lines.append(f"| {r['timestamp']} | {r['error_type']} | {msg} |")
    else:
        lines.append("_No incident found._")

    root = d["root_cause"]
    if root and "error" not in root:
        lines += [
            "", "## Root cause analysis",
            f"**Root cause:** {root.get('root_cause', '')}",
            "",
            f"**Suggested fix:** {root.get('suggested_fix', '')}",
        ]
        if root.get("error_chain"):
            lines += ["", "**Error chain:**", "", "```", root["error_chain"], "```"]

    lines += ["", "---", "_Generated by pylogtracer._"]
    return "\n".join(lines) + "\n"


# ── HTML ───────────────────────────────────────────────────────────
def _render_html(d: Dict) -> str:
    s, h = d["summary"], d["health"]
    e = _html.escape
    status = h.get("status", "?")
    color = {"OK": "#2e7d32", "WARNING": "#f9a825", "CRITICAL": "#c62828"}.get(status, "#555")

    parts = [
        "<!doctype html><html><head><meta charset='utf-8'>",
        f"<title>Log Analysis Report — {e(str(d['file']))}</title>",
        "<style>body{font-family:system-ui,Arial,sans-serif;margin:2rem;color:#222;}"
        "h1{font-size:1.5rem;}table{border-collapse:collapse;margin:.5rem 0;}"
        "th,td{border:1px solid #ddd;padding:6px 10px;text-align:left;font-size:.9rem;}"
        "th{background:#f5f5f5;}.status{font-weight:bold;color:" + color + ";}"
        "code{background:#f3f3f3;padding:1px 4px;border-radius:3px;}</style></head><body>",
        f"<h1>Log Analysis Report — <code>{e(str(d['file']))}</code></h1>",
        f"<p>Status: <span class='status'>{e(status)}</span> — {e(h.get('summary', ''))}</p>",
        "<h2>Summary</h2><ul>"
        f"<li>Total entries: <b>{s.get('total_entries', 0)}</b></li>"
        f"<li>Total errors: <b>{s.get('total_errors', 0)}</b></li>"
        f"<li>Incidents (clusters): <b>{s.get('total_clusters', 0)}</b></li>"
        f"<li>First error: {e(str(s.get('first_error') or '—'))}</li>"
        f"<li>Last error: {e(str(s.get('last_error') or '—'))}</li></ul>",
        "<h2>Error frequency</h2>",
    ]
    freq = d["frequency"]
    if freq:
        parts.append("<table><tr><th>Error type</th><th>Count</th></tr>")
        parts += [f"<tr><td>{e(str(k))}</td><td>{v}</td></tr>" for k, v in freq.items()]
        parts.append("</table>")
    else:
        parts.append("<p><em>No errors found.</em></p>")

    dur = d["duration"]
    parts.append("<h2>Last incident</h2>")
    if dur and "duration_human" in dur:
        parts.append(f"<p><em>Duration: {e(dur['duration_human'])} "
                     f"({e(str(dur.get('start')))} &rarr; {e(str(dur.get('end')))})</em></p>")
    if d["last_incident"]:
        parts.append("<table><tr><th>Time</th><th>Type</th><th>Message</th></tr>")
        for r in d["last_incident"]:
            parts.append(f"<tr><td>{e(r['timestamp'])}</td><td>{e(r['error_type'])}</td>"
                         f"<td>{e(r['primary_error'])}</td></tr>")
        parts.append("</table>")
    else:
        parts.append("<p><em>No incident found.</em></p>")

    root = d["root_cause"]
    if root and "error" not in root:
        parts += [
            "<h2>Root cause analysis</h2>",
            f"<p><b>Root cause:</b> {e(root.get('root_cause', ''))}</p>",
            f"<p><b>Suggested fix:</b> {e(root.get('suggested_fix', ''))}</p>",
        ]
        if root.get("error_chain"):
            parts.append(f"<pre>{e(root['error_chain'])}</pre>")

    parts.append("<hr><p><small>Generated by pylogtracer.</small></p></body></html>")
    return "".join(parts)
